/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inputcentar;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.DB;

/**
 *
 * @author hikme
 */
public class Clan extends javax.swing.JInternalFrame {

   
    /**
     * Creates new form Clan
     */
    public Clan() {
        initComponents();
    }

    Clan(String info) {
        initComponents();
        
        ArrayList<String[]> clanID = new ArrayList<>();
                try{
                    clanID = DB.IspisClan(clanID);
                }
                catch(Exception e){
                JOptionPane.showMessageDialog(this, "Mozda je baza prazna");
                }
                System.out.println(clanID.size());
          
                 for(int i=0; i<clanID.size(); i++){
                     System.out.println(String.valueOf(info.substring(info.length()- 1 )));
                     System.out.println(String.valueOf(clanID.get(i)[9]));
// 9    string.substring(string.length() - 1))
                     if(info.substring(info.length()- 1 ) == null ? String.valueOf(clanID.get(i)[9]) != null : !info.substring(info.length()- 1 ).equals(String.valueOf(clanID.get(i)[9]))) {
                combDodavanjeClana.addItem(String.valueOf(clanID.get(i)[0]) + " " + String.valueOf(clanID.get(i)[1]));
               }
    }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDodajClana = new javax.swing.JButton();
        combDodavanjeClana = new javax.swing.JComboBox<>();

        setClosable(true);
        setForeground(java.awt.Color.gray);
        setMaximizable(true);
        setResizable(true);
        setTitle("Dodavanje clana");
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(580, 300));

        btnDodajClana.setText("Dodaj");
        btnDodajClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajClanaActionPerformed(evt);
            }
        });

        combDodavanjeClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combDodavanjeClanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDodajClana, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(211, 211, 211))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(combDodavanjeClana, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(combDodavanjeClana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(btnDodajClana)
                .addGap(46, 46, 46))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajClanaActionPerformed
        
    }//GEN-LAST:event_btnDodajClanaActionPerformed

    private void combDodavanjeClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combDodavanjeClanaActionPerformed
        
    }//GEN-LAST:event_combDodavanjeClanaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajClana;
    private javax.swing.JComboBox<String> combDodavanjeClana;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    void main(String[] info) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
