/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inputcentar;


import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.DB;

/**
 *
 * @author hikme
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnPrijava = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtLozinka = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        btnPregledTimova = new javax.swing.JButton();
        btnUnosUposlenika = new javax.swing.JButton();
        btnEvidencijaRada = new javax.swing.JButton();
        btnOdjava = new javax.swing.JButton();
        btnRaspored = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela1 = new javax.swing.JTable();
        btnDodajDan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnNazadRaspored = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        Musko = new javax.swing.JRadioButton();
        Zensko = new javax.swing.JRadioButton();
        txtGrad = new javax.swing.JTextField();
        txtBroj = new javax.swing.JTextField();
        txtEmail1 = new javax.swing.JTextField();
        txtTimID = new javax.swing.JTextField();
        btnDa = new javax.swing.JRadioButton();
        btnNe = new javax.swing.JRadioButton();
        btnUnesi = new javax.swing.JButton();
        txtNazad = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtRodjenje = new com.toedter.calendar.JDateChooser();
        txtZaposlenje = new com.toedter.calendar.JDateChooser();
        txtSifra1 = new javax.swing.JPasswordField();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        btnNazadUpravljanjeTimovima = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        combOdabirTima = new javax.swing.JComboBox<>();
        btnDodajClan = new javax.swing.JButton();
        btnKreirajTim = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jL18 = new javax.swing.JLabel();
        jL19 = new javax.swing.JLabel();
        jL20 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jComboPolaznici = new javax.swing.JComboBox<>();
        jComboDatumi = new javax.swing.JComboBox<>();

        jLabel16.setText("jLabel16");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("e-mail");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("lozinka");

        btnPrijava.setText("Potvrdi");
        btnPrijava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrijavaActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setText("PRIJAVA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(jLabel15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(382, 382, 382)
                        .addComponent(btnPrijava, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(txtLozinka))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel15)
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(btnPrijava, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );

        jPanel1.add(jPanel2, "card2");

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        btnPregledTimova.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnPregledTimova.setText("Pregled timova");
        btnPregledTimova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPregledTimovaActionPerformed(evt);
            }
        });

        btnUnosUposlenika.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnUnosUposlenika.setText("Unos uposlenika");
        btnUnosUposlenika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosUposlenikaActionPerformed(evt);
            }
        });

        btnEvidencijaRada.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEvidencijaRada.setText("Evidencija rada");
        btnEvidencijaRada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvidencijaRadaActionPerformed(evt);
            }
        });

        btnOdjava.setText("Odjava");
        btnOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdjavaActionPerformed(evt);
            }
        });

        btnRaspored.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRaspored.setText("Pregled rasporeda");
        btnRaspored.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRasporedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(355, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnOdjava)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnUnosUposlenika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEvidencijaRada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRaspored, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPregledTimova, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(367, 367, 367))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(btnPregledTimova, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnUnosUposlenika, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnEvidencijaRada, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnRaspored, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(btnOdjava)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, "card3");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        Tabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Broj", "Datum", "Pocetak", "Kraj"
            }
        ));
        jScrollPane1.setViewportView(Tabela1);

        btnDodajDan.setText("DODAJ DAN");
        btnDodajDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajDanActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("RASPORED PRAKSE");

        btnNazadRaspored.setText("Nazad");
        btnNazadRaspored.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadRasporedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(74, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDodajDan, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(106, 106, 106))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnNazadRaspored)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(300, 300, 300))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnNazadRaspored, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDodajDan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, "card4");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Ime");

        jLabel5.setText("Prezime");

        jLabel6.setText("Spol");

        jLabel7.setText("Datum rodjenja");

        jLabel8.setText("Datum zaposlenja");

        jLabel9.setText("Grad");

        jLabel10.setText("Broj tel");

        jLabel11.setText("Email");

        jLabel12.setText("Lozinka");

        jLabel13.setText("Tim id");

        jLabel14.setText("Admin");

        txtIme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImeActionPerformed(evt);
            }
        });

        txtPrezime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrezimeActionPerformed(evt);
            }
        });

        buttonGroup1.add(Musko);
        Musko.setText("Musko");

        buttonGroup1.add(Zensko);
        Zensko.setText("Zensko");
        Zensko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZenskoActionPerformed(evt);
            }
        });

        buttonGroup2.add(btnDa);
        btnDa.setText("Da");

        buttonGroup2.add(btnNe);
        btnNe.setText("Ne");

        btnUnesi.setText("UNESI");
        btnUnesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiActionPerformed(evt);
            }
        });

        txtNazad.setText("Nazad");
        txtNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNazadActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel17.setText("UNOS KORISNIKA");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUnesi, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(394, 394, 394))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(Musko)
                                .addGap(18, 18, 18)
                                .addComponent(Zensko))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtRodjenje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtZaposlenje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnDa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNe))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtSifra1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtGrad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                .addComponent(txtBroj, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtEmail1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTimID, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtNazad)
                        .addGap(293, 293, 293)
                        .addComponent(jLabel17)
                        .addContainerGap(342, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9)
                                    .addComponent(txtGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtNazad))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(txtBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Musko)
                            .addComponent(Zensko)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11)
                            .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtRodjenje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtZaposlenje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtSifra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtTimID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(btnDa)
                    .addComponent(btnNe))
                .addGap(18, 18, 18)
                .addComponent(btnUnesi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jPanel1.add(jPanel5, "card5");

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setText("UPRAVLJANJE TIMOVIMA");

        btnNazadUpravljanjeTimovima.setText("NAZAD");
        btnNazadUpravljanjeTimovima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadUpravljanjeTimovimaActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ime", "Prezime", "E-mail", "Grad"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        combOdabirTima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combOdabirTimaActionPerformed(evt);
            }
        });

        btnDodajClan.setText("DODAJ CLANA");
        btnDodajClan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajClanActionPerformed(evt);
            }
        });

        btnKreirajTim.setText("KREIRAJ TIM");
        btnKreirajTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnNazadUpravljanjeTimovima, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKreirajTim, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(363, 363, 363)
                .addComponent(btnDodajClan, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(combOdabirTima, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(307, 307, 307))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combOdabirTima, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnDodajClan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNazadUpravljanjeTimovima, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKreirajTim, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel1.add(jPanel6, "card7");

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Broj prakse", "Datum", "Pocetak", "Vrijeme provedeno", "Tim", "Opis rada"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton1.setText("ODJAVA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jL18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jL18.setText("jLabel18");

        jL19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jL19.setText("jLabel19");

        jL20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jL20.setText("jLabel20");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jL18, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(jL19, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                        .addComponent(jL20, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL19)
                    .addComponent(jL20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jPanel1.add(jPanel7, "card6");

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton1.setText("DODAJ EVIDENCIJU");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 389, 256, 53));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ime", "Prezime", "Email", "Datum", "Sati", "Opis"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jPanel8.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 92, 897, 150));

        jComboPolaznici.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Svi polaznici" }));
        jComboPolaznici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboPolazniciActionPerformed(evt);
            }
        });
        jPanel8.add(jComboPolaznici, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 277, 43));

        jComboDatumi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Svi datumi" }));
        jComboDatumi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboDatumiActionPerformed(evt);
            }
        });
        jPanel8.add(jComboDatumi, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 180, -1));

        jPanel1.add(jPanel8, "card8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrijavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrijavaActionPerformed
        // TODO add your handling code here:
        ArrayList<uposlenik> ko=new ArrayList<>();
        DB.IspisKorisnici(ko);
        for(int i=0; i<ko.size();i++){
            if(ko.get(i).email.equals(txtEmail.getText()) && ko.get(i).lozinka.equals(txtLozinka.getText())){
                if(ko.get(i).admin==1){
                jPanel2.setVisible(false);
                jPanel3.setVisible(true);
                jPanel4.setVisible(false);
                jPanel5.setVisible(false);
                jPanel7.setVisible(false);
                break;
                }
                else{
                jPanel2.setVisible(false);
                jPanel3.setVisible(false);
                jPanel4.setVisible(false);
                jPanel7.setVisible(true);
                jPanel5.setVisible(false);
                KorisnikPregled(ko.get(i));
                break;
                }
            }
        }
    }//GEN-LAST:event_btnPrijavaActionPerformed
    private void KorisnikPregled(uposlenik kor){
        jL18.setText("Dobrodosao "+kor.getIme());
        jL19.setText("Tim "+kor.getTim_id());
        double SatiUkupno=0.0;
        ArrayList<String[]> str= new ArrayList();
        str=DB.IspisUpEv(str,kor.getEmail());
        for(int i=0; i<str.size(); i++){
            SatiUkupno+=Double.parseDouble(str.get(i)[3]);
        }
        jL20.setText("Ukupno sati: "+ SatiUkupno);
        for(int i=0; i<str.size(); i++){
           String nestoo[] = {String.valueOf(str.get(i)[0]), str.get(i)[1], str.get(i)[2],String.valueOf(str.get(i)[3]), String.valueOf(str.get(i)[4]),str.get(i)[5]};
           DefaultTableModel tbModel=(DefaultTableModel) jTable1.getModel();
           tbModel.addRow(nestoo);    
        }
    }
    //NE RADI  // e
    private void PanelPrikaz(int i){
                jPanel2.setVisible(false);
                jPanel3.setVisible(false);
                jPanel4.setVisible(false);
                jPanel5.setVisible(false);
                jPanel6.setVisible(false);
                jPanel7.setVisible(false);
                jPanel8.setVisible(false);

                String str = "jPanel"+i;
                
    }
    private void btnPregledTimovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPregledTimovaActionPerformed
                jPanel2.setVisible(false);
                jPanel3.setVisible(false);
                jPanel4.setVisible(false);
                jPanel5.setVisible(false);
                jPanel6.setVisible(true);
                jPanel7.setVisible(false);
                jPanel8.setVisible(false);
                ArrayList<String[]> timID = new ArrayList<>();
                try{
                    timID = DB.IspisTim(timID);
                }
                catch(Exception e){
                JOptionPane.showMessageDialog(this, "Mozda je baza prazna");
                }
                System.out.println(timID.size());
          
                 for(int i=0; i<timID.size(); i++){
                combOdabirTima.addItem(String.valueOf(timID.get(i)[1]));
               }
    }//GEN-LAST:event_btnPregledTimovaActionPerformed

    private void btnUnosUposlenikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosUposlenikaActionPerformed
        // TODO add your handling code here:
                jPanel2.setVisible(false);
                jPanel3.setVisible(false);
                jPanel4.setVisible(false);
                jPanel5.setVisible(true);
                jPanel7.setVisible(false);
                jPanel8.setVisible(false);
                jPanel6.setVisible(false);
    }//GEN-LAST:event_btnUnosUposlenikaActionPerformed

    private void btnOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjavaActionPerformed
        // TODO add your handling code here:
                jPanel2.setVisible(true);
                jPanel3.setVisible(false);
                jPanel4.setVisible(false);
                jPanel5.setVisible(false);
                jPanel7.setVisible(false);
                jPanel8.setVisible(false);
                jPanel6.setVisible(false);
    }//GEN-LAST:event_btnOdjavaActionPerformed

    private void txtImeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImeActionPerformed

    private void txtPrezimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrezimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrezimeActionPerformed

    private void ZenskoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZenskoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZenskoActionPerformed

    private void txtNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNazadActionPerformed
        // TODO add your handling code here:
        jPanel2.setVisible(false);
                jPanel3.setVisible(true);
                jPanel4.setVisible(false);
                jPanel5.setVisible(false);
                jPanel7.setVisible(false);
                jPanel8.setVisible(false);
                jPanel6.setVisible(false);
    }//GEN-LAST:event_txtNazadActionPerformed
//NIZ CUVA IME PREZIME I EMAIL //
 ArrayList<String[]> imena = new ArrayList();
//NIZ CUVA DATUM //
 ArrayList<String> datumi= new ArrayList();
// FILTERI ZA EVIDENCIJU (DATUM / IME) //
String FilterIme="";
String FilterDatum="";
private void Filtriranje(){
    DefaultTableModel Model=(DefaultTableModel) jTable3.getModel();
    Model.setRowCount(0);
    ArrayList<String[]> str=new ArrayList();
    str=DB.IspisEvidencija(str);
  if(FilterIme=="" && FilterDatum==""){
     for(int i=0; i<str.size(); i++)
     {
     String redTabele[]={str.get(i)[0],str.get(i)[1],str.get(i)[2],str.get(i)[3],str.get(i)[4],str.get(i)[5]};
     Model.addRow(redTabele);
     }
  }    
  else if(FilterIme=="" && FilterDatum!=""){
      for(int i=0; i<str.size(); i++)
      {
          if(str.get(i)[3].equals(FilterDatum)){
            String redTabele[]={str.get(i)[0],str.get(i)[1],str.get(i)[2],str.get(i)[3],str.get(i)[4],str.get(i)[5]};
            Model.addRow(redTabele);
          }
      }
  }
  else if(FilterIme!="" && FilterDatum==""){
      for(int i=0; i<str.size(); i++)
      {
          if(str.get(i)[2].equals(FilterIme)){
             String redTabele[]={str.get(i)[0],str.get(i)[1],str.get(i)[2],str.get(i)[3],str.get(i)[4],str.get(i)[5]};
             Model.addRow(redTabele);
          }
      }
  }
  else{
      for(int i=0; i<str.size(); i++){
      if(str.get(i)[2].equals(FilterIme) && str.get(i)[3].equals(FilterDatum)){
             String redTabele[]={str.get(i)[0],str.get(i)[1],str.get(i)[2],str.get(i)[3],str.get(i)[4],str.get(i)[5]};
             Model.addRow(redTabele);
      }
     }
  }
}


    private void btnEvidencijaRadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvidencijaRadaActionPerformed
        // TODO add your handling code here:
                imena.clear();
                datumi.clear();
                jPanel2.setVisible(false);
                jPanel3.setVisible(false);
                jPanel4.setVisible(false);
                jPanel5.setVisible(false);     
                jPanel6.setVisible(false);
                jPanel7.setVisible(false);
                jPanel8.setVisible(true);
                ArrayList<String[]> str= new ArrayList();
               str=DB.IspisEvidencija(str);
                DefaultTableModel Model=(DefaultTableModel) jTable3.getModel();
                Model.setRowCount(0);
        for(int i=0; i<str.size(); i++){
           String nestoo[] = {String.valueOf(str.get(i)[0]), str.get(i)[1], str.get(i)[2],String.valueOf(str.get(i)[3]), String.valueOf(str.get(i)[4]),str.get(i)[5]};
           Model.addRow(nestoo);
           int brojac=0; // ZA IMENA
           int brojac1=0;  // ZA DATUME
           if(!imena.isEmpty()){
           for(int j=0; j<imena.size(); j++){
               if(str.get(i)[2].equals(imena.get(j)[2])){
                  brojac++;               
               } 
           }
           }
           if(brojac==0){
               String nizIme[]={str.get(i)[0],str.get(i)[1],str.get(i)[2]};
               imena.add(nizIme);
               jComboPolaznici.addItem(nizIme[0]+" "+nizIme[1]+" "+nizIme[2]);
           }
           
           if(!datumi.isEmpty()){
           for(int k=0; k<datumi.size(); k++){
               if(str.get(i)[3].equals(datumi.get(k))){
                  brojac1++;               
               } 
           }
           }
           if(brojac1==0){
               String nizDatum=str.get(i)[3];
               datumi.add(nizDatum);
               jComboDatumi.addItem(nizDatum);
           }
           
        }
       
    }//GEN-LAST:event_btnEvidencijaRadaActionPerformed

    private void btnUnesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiActionPerformed
        // TODO add your handling code here:
        int bj=0; 
        int k=0;
        int k1=0;
        int timid=0;
        int spl=0;
        int varadmin=0;
        try{
              bj=Integer.parseInt(String.valueOf(txtBroj.getText()));
              
            }
            catch(Exception e){
                k++;
            }
        try{
              timid=Integer.parseInt(String.valueOf(txtTimID.getText()));
            }
            catch(Exception e){
                k1++;
            }
         if(Musko.isSelected()){
            spl=0;
           
        }
        else if(Zensko.isSelected()){
            spl=1;
           
        }
         
        if(btnDa.isSelected()){
            varadmin=1;
           
        }
        else if(btnNe.isSelected()){
            varadmin=0;
           
        }
        
        if(!Musko.isSelected() && !Zensko.isSelected())
        {
            JOptionPane.showMessageDialog(this, "Morate oznaciti musko/zensko");
        }
        else if(!btnDa.isSelected() && !btnNe.isSelected())
        {
            JOptionPane.showMessageDialog(this, "Morate oznaciti da/ne");
        }
       else if(txtIme.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Morate unijeti ime");
        }
        else if(txtPrezime.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Morate unijeti prezime");
        }
        else if(txtBroj.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Morate unijeti broj");
        }
        else if(txtRodjenje.getDate() == null){
            JOptionPane.showMessageDialog(this,"Morate unijeti datum rodjenja");
        }
        else if(txtZaposlenje.getDate() == null){
            JOptionPane.showMessageDialog(this,"Morate unijeti datum zaposlenja");
        }
        else if(txtGrad.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Morate unijeti ime grada");
        }
        else if(txtEmail1.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Morate unijeti email");
        }
        else if(txtSifra1.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Morate unijeti sifra");
        }
        else if(txtTimID.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Morate unjeti id TIMa");
        }
        else if(k!=0){
            JOptionPane.showMessageDialog(this,"Mora biti broj (telefon, koristiti samo brojeve)"); 
        }
        else if(k1!=0){
            JOptionPane.showMessageDialog(this,"Mora biti broj tima"); 
        }
        else{
            java.sql.Date rDate = new java.sql.Date(txtRodjenje.getDate().getTime());
            java.sql.Date zDate = new java.sql.Date(txtZaposlenje.getDate().getTime());
            DB.UnosUposlenik(txtIme.getText(), txtPrezime.getText(), spl, rDate, zDate, txtGrad.getText(), txtBroj.getText(), txtEmail1.getText(), txtSifra1.getText(), timid, varadmin);
            JOptionPane.showMessageDialog(this,"Uspjesno unesen korisnik!"); 
            txtIme.setText("");
            txtPrezime.setText("");
            txtGrad.setText("");
            txtBroj.setText("");
            txtEmail1.setText("");
            txtSifra1.setText("");
            txtIme.setText("");
            Musko.setSelected(false);
            Zensko.setSelected(false);
            btnDa.setSelected(false);
            btnNe.setSelected(false);
            txtRodjenje.setCalendar(null);
            txtZaposlenje.setCalendar(null);
        }
    }//GEN-LAST:event_btnUnesiActionPerformed

    private void btnRasporedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRasporedActionPerformed
        // TODO add your handling code here:
                jPanel2.setVisible(false);
                jPanel3.setVisible(false);
                jPanel4.setVisible(true);
                jPanel5.setVisible(false);
                jPanel7.setVisible(false);
                jPanel8.setVisible(false);
                jPanel6.setVisible(false);
                
                         ArrayList<String[]> ras = new ArrayList<>();
        try{
            ras=DB.IspisRaspored(ras);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Mozda je baza prazna");
        }
        String nesto;
        DefaultTableModel tblModel=(DefaultTableModel) Tabela1.getModel();
        tblModel.setRowCount(0);
        for(int i=0; i<ras.size(); i++){
           String nestoo[] = {String.valueOf(ras.get(i)[0]), ras.get(i)[1], ras.get(i)[2], String.valueOf(ras.get(i)[3])};
           
           tblModel.addRow(nestoo);
           
        }
    }//GEN-LAST:event_btnRasporedActionPerformed

    private void btnDodajDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajDanActionPerformed
        // TODO add your handling code here:
        Opis op = new Opis();
        this.getLayeredPane().add(op);
        try {
        op.setSelected(true);
        op.toFront();
    } catch (java.beans.PropertyVetoException e) {}
        
          
  
    }//GEN-LAST:event_btnDodajDanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           jPanel2.setVisible(true);
                jPanel3.setVisible(false);
                jPanel4.setVisible(false);
                jPanel5.setVisible(false);
                jPanel7.setVisible(false);
                jPanel8.setVisible(false);
                jPanel6.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnNazadRasporedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadRasporedActionPerformed
        // TODO add your handling code here:
                jPanel2.setVisible(false);
                jPanel3.setVisible(true);
                jPanel4.setVisible(false);
                jPanel5.setVisible(false);
                jPanel7.setVisible(false);
                jPanel8.setVisible(false);
                jPanel6.setVisible(false);
    }//GEN-LAST:event_btnNazadRasporedActionPerformed

    private void btnNazadUpravljanjeTimovimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadUpravljanjeTimovimaActionPerformed
        jPanel2.setVisible(false);
                jPanel3.setVisible(true);
                jPanel4.setVisible(false);
                jPanel5.setVisible(false);
                jPanel7.setVisible(false);
                jPanel8.setVisible(false);
                jPanel6.setVisible(false);
    }//GEN-LAST:event_btnNazadUpravljanjeTimovimaActionPerformed

    private void combOdabirTimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combOdabirTimaActionPerformed
        Object selectedItem = combOdabirTima.getSelectedItem();
        if (selectedItem != null)
        {    
            ArrayList<String[]> Rezultat = new ArrayList<>();
            String selectedItemStr = selectedItem.toString();
            Rezultat=DB.IspisTimTabela(Rezultat,selectedItemStr); // Some method that takes a string parameter.
            
             String nesto;
            DefaultTableModel tblModel=(DefaultTableModel) jTable2.getModel();
            tblModel.setRowCount(0);
            for(int i=0; i<Rezultat.size(); i++){
                String nestoo[] = {String.valueOf(Rezultat.get(i)[0]), Rezultat.get(i)[1], Rezultat.get(i)[2], String.valueOf(Rezultat.get(i)[3])};
           
                tblModel.addRow(nestoo);
           
        }
        }
        
    }//GEN-LAST:event_combOdabirTimaActionPerformed

    private void btnDodajClanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajClanActionPerformed
        // TODO add your handling code here:
        
        String info=String.valueOf(combOdabirTima.getSelectedItem());; //put jTextField1's value in the array.
        Clan cl = new Clan(info);
        this.getLayeredPane().add(cl);
        try {
        cl.setSelected(true);
        cl.toFront();
        
    } catch (java.beans.PropertyVetoException e) {}
        
    }//GEN-LAST:event_btnDodajClanActionPerformed

    private void btnKreirajTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajTimActionPerformed
        Tim tim = new Tim();
        this.getLayeredPane().add(tim);
        try {
        tim.setSelected(true);
        tim.toFront();
    } catch (java.beans.PropertyVetoException e) {}
    }//GEN-LAST:event_btnKreirajTimActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
          UnosEvidencija cl = new UnosEvidencija();
        this.getLayeredPane().add(cl);
        try {
        cl.setVisible(true);
        cl.setDefaultCloseOperation(1);
        cl.pack();
        cl.setSelected(true);
        cl.toFront();
    } catch (java.beans.PropertyVetoException e) {}
       
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jComboPolazniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboPolazniciActionPerformed
          
        if(!jComboPolaznici.getSelectedItem().toString().equals("Svi polaznici")){
            FilterIme=imena.get(jComboPolaznici.getSelectedIndex()-1)[2];
        }        // TODO add your handling code here:
        else{
            FilterIme="";
        }
        Filtriranje();
    }//GEN-LAST:event_jComboPolazniciActionPerformed

    private void jComboDatumiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboDatumiActionPerformed
        // TODO add your handling code here:
        
        if(!jComboDatumi.getSelectedItem().toString().equals("Svi datumi")){
            FilterDatum=jComboDatumi.getSelectedItem().toString();
        } 
        else{
            FilterDatum="";
        }
        Filtriranje();
    }//GEN-LAST:event_jComboDatumiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Musko;
    private javax.swing.JTable Tabela1;
    private javax.swing.JRadioButton Zensko;
    private javax.swing.JRadioButton btnDa;
    private javax.swing.JButton btnDodajClan;
    private javax.swing.JButton btnDodajDan;
    private javax.swing.JButton btnEvidencijaRada;
    private javax.swing.JButton btnKreirajTim;
    private javax.swing.JButton btnNazadRaspored;
    private javax.swing.JButton btnNazadUpravljanjeTimovima;
    private javax.swing.JRadioButton btnNe;
    private javax.swing.JButton btnOdjava;
    private javax.swing.JButton btnPregledTimova;
    private javax.swing.JButton btnPrijava;
    private javax.swing.JButton btnRaspored;
    private javax.swing.JButton btnUnesi;
    private javax.swing.JButton btnUnosUposlenika;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> combOdabirTima;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboDatumi;
    private javax.swing.JComboBox<String> jComboPolaznici;
    private javax.swing.JLabel jL18;
    private javax.swing.JLabel jL19;
    private javax.swing.JLabel jL20;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField txtBroj;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtGrad;
    private javax.swing.JTextField txtIme;
    private javax.swing.JPasswordField txtLozinka;
    private javax.swing.JButton txtNazad;
    private javax.swing.JTextField txtPrezime;
    private com.toedter.calendar.JDateChooser txtRodjenje;
    private javax.swing.JPasswordField txtSifra1;
    private javax.swing.JTextField txtTimID;
    private com.toedter.calendar.JDateChooser txtZaposlenje;
    // End of variables declaration//GEN-END:variables
}
