package inputcentar;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import util.DB;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell Pc
 */
public class Opis extends javax.swing.JInternalFrame {

    /**
     * Creates new form Opis
     */
    public Opis() {
        initComponents();
          
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnIzlazDodavanjeDana = new javax.swing.JButton();
        btnSacuvajDan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dtmDan = new com.toedter.calendar.JDateChooser();
        double min = 0.00;
        double value = 17.00;
        double max = 23.59;
        double stepSize = 1.00;
        SpinnerNumberModel model1 = new SpinnerNumberModel(value, min, max, stepSize);
        pocetakRada = new javax.swing.JSpinner(model1);
        double min2 = 0.00;
        double value2 = 19.00;
        double max2 = 23.59;
        double stepSize2 = 1.00;
        SpinnerNumberModel model2 = new SpinnerNumberModel(value2, min2, max2, stepSize2);
        krajRada = new javax.swing.JSpinner(model2);

        setClosable(true);
        setForeground(java.awt.Color.gray);
        setMaximizable(true);
        setResizable(true);
        setTitle("Dodavanje dana");
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIzlazDodavanjeDana.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnIzlazDodavanjeDana.setText("IZLAZ");
        btnIzlazDodavanjeDana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzlazDodavanjeDanaActionPerformed(evt);
            }
        });

        btnSacuvajDan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSacuvajDan.setText("SACUVAJ");
        btnSacuvajDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajDanActionPerformed(evt);
            }
        });

        jLabel1.setText("Datum");

        jLabel2.setText("Pocetak rada");

        jLabel3.setText("Kraj rada");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(jLabel1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pocetakRada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtmDan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(krajRada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btnSacuvajDan)
                        .addGap(125, 125, 125)
                        .addComponent(btnIzlazDodavanjeDana)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(dtmDan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pocetakRada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(krajRada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvajDan)
                    .addComponent(btnIzlazDodavanjeDana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzlazDodavanjeDanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzlazDodavanjeDanaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnIzlazDodavanjeDanaActionPerformed

    private void btnSacuvajDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajDanActionPerformed
        // TODO add your handling code here:
        java.sql.Date rDate = new java.sql.Date(dtmDan.getDate().getTime());
        Double pocetak = (Double)pocetakRada.getValue();
        Double kraj = (Double)krajRada.getValue();
            DB.UnosDan(rDate, pocetak, kraj);
            JOptionPane.showMessageDialog(this,"Uspjesno unesen dan!"); 
    }//GEN-LAST:event_btnSacuvajDanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzlazDodavanjeDana;
    private javax.swing.JButton btnSacuvajDan;
    private com.toedter.calendar.JDateChooser dtmDan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner krajRada;
    private javax.swing.JSpinner pocetakRada;
    // End of variables declaration//GEN-END:variables
}
